### ISSUE TITLE
Request: Using concourse metadata in the Gerrit output message

### ISSUE THREAD

**Issue by arekmano** [google/concourse-resources#10]
Concourse provides <a href="https://concourse.ci/implementing-resources.html#resource-metadata">Metadata</a> access to Resources in the form of environment variables. It would be neat if we could use these in the output messages for the Gerrit resource.

Having the configuration look something like this:
```
put: example-gerrit
params:
  repository: example-gerrit
  message: CI passed! http://URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_ID
  labels: {Verified: 1}
```
output the following message:
```
CI passed! http://URL/teams/example_team/pipelines/example_pipleine/jobs/example_job/builds/1
```

Similar functionality has been added to the email resource <a href="https://github.com/pivotal-cf/email-resource/pull/12">here</a>
