### ISSUE TITLE
How to only be triggered by master, not by refs/for/master

### ISSUE THREAD

**Issue by CamiloGarciaLaRotta** [google/concourse-resources#14]
Hi, 

I have 2 Gerrit resources that follow the **Master** branch and the open **Code-Reviews** (`refs/for/master`).

Unfortunately, sometimes `gerrit-master` gets triggered by commits pushed to `refs/for/master`, which evidently haven't been merged into master and `gerrit-code-review` doesn't pick up new commits pushed to `refs/for/master`

I have read through [Gerrit's query documentation](https://gerrit-documentation.storage.googleapis.com/Documentation/2.14.2/user-search.html) but so far none of the related operators seem to do the trick: `is: status: branch: ref:`

```yml
- name: gerrit-master
  type: gerrit
  source:
    query: project:<PROJECT> branch:master
    ...
    
- name: gerrit-code-review
  type: gerrit
  source:
    query: project:<PROJECT> is:open
    ...
```

Any advice on how to configure the resource is appreciated,

Thanks in advance

**Comment by CamiloGarciaLaRotta** [comment]
Alright, for anyone facing the same issue:

The following combination of query operators seem to fix the first issue: commits for code-review only trigger `gerrit-code-review` and merged code-reviews only trigger `gerrit-master`.

```yml
- name: gerrit-master
    query: project:<PROJECT> branch:master status:closed
    
- name: gerrit-code-review
    query: project:<PROJECT> branch:master status:open
```

As for ensuring all code-reviews get picked up by `gerrit-code-review` resource:
some commits are still ignored (specially if the time between them is short), but it is none the less more stable than with my original query operators.
