### ISSUE TITLE
README example does not work

### ISSUE THREAD

**Issue by arekmano** [google/concourse-resources#8]
When I base myself off the configuration example found in the README. configuration uploading generates an error within Concourse.

### Configuration file used
```
resource_types:
- name: gerrit
  type: docker-image
  source:
    repository: us.gcr.io/concourse-resources/gerrit-resource

resources:
- name: main-gerrit
  type: gerrit
  source:
    url: https://{{GERRIT_URL}}/
    query: status:open project:{{PROJECT_NAME}}
    username: {{USERNAME}}
    password: {{PASSWORD}}

jobs:
- name: Test-CI
  plan:
  # Trigger this job for every new patch set
  - get: main-gerrit
    version: every
    trigger: true

  - task: ls-it
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: ls

  # After a successfuly build, mark the patch set Verified +1
  - put: main-gerrit
    message: CI passed!
    labels: {Verified: 1}
```

### Error message

```
error: invalid configuration:
unknown/extra keys:
  - jobs[0].plan[2].labels
  - jobs[0].plan[2].message

```
